---
title: "DDS_Project_JR_LM"
author: "JR"
date: "6/4/2021"
output: html_document
---

# Introduction
# Reed and Miller Consulting has been hired by Budweiser to perform data analytics in order to aid in their business decision making process.  We have received specific information regarding various types of beers as well as breweries in the United States which will be used to conduct our analysis.  We have also been given specific questions that we will seek to answer and will also strive to report back other interesting insights that may be deemed pertinent and useful to their business.

# Code purpose
# The code below is broken down into 2 categories.  The information preceded by # is explanatory information while the other information is the actual code used to perform our data analysis.

# load pertinent code libraries
library(ggplot2)
library(magrittr)
library(dplyr)
library(GGally)
library(tibble)
library(class)
library(caret)
library(e1071)
library(readr)

# load the Brewery csv file
Breweries = read.csv(file.choose(), header = TRUE)
summary(Breweries)

# load the Beers csv file
Beers = read.csv(file.choose(), header = TRUE)
summary(Beers)

# Question 1:  
# How many breweries in each state?  
Breweries %>% count(State, sort = TRUE)
# We then exported the data to excel to format into a table given the large amount of data
#????? I did this manually.....any thoughts on how to code this???  write.csv(Breweries %>% count(State, sort = TRUE), path = "Breweries_State.csv")

# ????Not sure if this graph was useful as it had so many data points so didn't include.  Any thoughts on how to visually answer this question.
# ?????Breweries %>% ggplot(aes(x = State)) + geom_bar(color="black", fill = "red", binwidth = 20)

# Question 2:  
# Merge the two data files provided by the client so that we can perform analysis on a single document and perform a deeper and more thorough analysis
# Steps taken:
# Change column names in Beers file to match up with Brewery file
colnames(Beers)[5] = "Brew_ID"
colnames(Beers)[1] = "Beer_Name"
summary(Beers)
# Change column name in Brewery file to clarify Beer name
colnames(Breweries)[2] = "Brewery_Name"
summary(Breweries)
# Merge Beers and Breweries data frames into one
Beer_Brew_Combo = merge(Beers, Breweries,c("Brew_ID"))
summary(Beer_Brew_Combo)
# Print first 6 rows in merged data frame
head(Beer_Brew_Combo, 6)
# Print last 6 rows in merged data frame
tail(Beer_Brew_Combo, 6)


# Question 3: 
# Address the missing values in each column.
# ????Logan:  not exactly sure what to do here.  I removed it below but am completely open to thoughts


# Question 4:  
# Compute the median alcohol content (ABV) and international bitterness unit (IBU) for each state. 
# Plot a bar chart to compare.
# Create new data from that removes NA's in ABV column then calculates median for each state
BBC_Median_ABV = Beer_Brew_Combo %>% filter(!is.na(ABV)) %>% group_by(State) %>% summarise_at(vars(ABV),list(name = median)) %>% rename(Median_ABV = name)

# Plot Median ABV by State.....LOgan, could definitely use your help with making this "pretty"
BBC_Median_ABV %>% ggplot(aes(x = State, y = Median_ABV, ylim(0.03, 0.06))) + geom_bar(stat = 'identity') + ggtitle("Median ABV By State") + geom_text(aes(label=Median_ABV), position=position_dodge(width=0.9),vjust=-.25)

# Create new data from that removes NA's in IBU column then calculates median for each state
BBC_Median_IBU = Beer_Brew_Combo %>% filter(!is.na(IBU)) %>% group_by(State) %>% summarise_at(vars(IBU),list(name = median)) %>% rename(Median_IBU = name)

# Plot Median IBU by State.....same here, Logan could definitely use your help with making this "pretty"
BBC_Median_IBU %>% ggplot(aes(x = State, y = Median_IBU)) + geom_bar(stat = 'identity') + ggtitle("Median IBU By State") + geom_text(aes(label=Median_IBU), position=position_dodge(width=0.9),vjust=-.25)

# Logan....any thoughts on how to export this data to a table???
print(BBC_Median_ABV)
print(BBC_Median_IBU)

# Question 5:  
# Which state has the maximum alcoholic (ABV) beer? Colorado
Beer_Brew_Combo[which.max(Beer_Brew_Combo$ABV),]

# Which state has the most bitter (IBU) beer? Oregon
Beer_Brew_Combo[which.max(Beer_Brew_Combo$IBU),]


#Question 6: 
# Comment on the summary statistics and distribution of the ABV variable.
# Count number of NA's and total ABV = 62
sum(is.na(Beer_Brew_Combo$ABV))
# total NA's = 62 which represents 2.6% of 2410 total sampled beers which is unlikely to skew the overall result

# Summary Statistics of ABV - Histogram
Beer_Brew_Combo %>% filter(!is.na(ABV)) %>% ggplot(aes(x = ABV)) + geom_histogram()
# Logan....would probably be good to add to this graph with summary stats, just didn't get there yet, and is another one that needs to be cleaned up

# Summary Statistics of ABV - Boxplot
Beer_Brew_Combo %>% filter(!is.na(ABV)) %>% ggplot(aes(x = ABV)) + geom_boxplot()
# same here.....would probably be good to add to this graph with summary stats, just didn't get there yet, and is another one that needs to be cleaned up


# Question 7:  
# Is there an apparent relationship between the bitterness of the beer (IBU) and its alcoholic content (ABV)? Draw a scatter plot.  Make your best judgment of a relationship and EXPLAIN your answer.
# Correlation coefficient = 0.671
# The scatter plot clearly evidences a positive correlation / relationship
# Add more here.....
Beer_Brew_Combo %>% filter(!is.na(ABV) | !is.na(IBU)) %>% select(ABV, IBU) %>% ggpairs()
Beer_Brew_Combo %>% filter(!is.na(ABV) | !is.na(IBU)) %>%  ggplot(aes(x = ABV, y = IBU)) + geom_point() + geom_smooth()
# This relationship makes me wonder if there is a way to use the ABV values to estimate IBU blanks and vice versa.....maybe this is what he is hinting at....I tried messing with this in excel by estimating an ABV value based on the IBU value but didn't make any headway....


# Question 8:  
# Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA).  You decide to use KNN classification to investigate this relationship.  Provide statistical evidence one way or the other. 
#In addition, while you have decided to use KNN to investigate this relationship (KNN is required) you may also feel free to supplement your response to this question with any other methods or techniques you have learned.  Creativity and alternative solutions are always encouraged. 
# I just did KNN so if you want to do NB then have at it!

# Create dataframe with only Ale and IPA beers
Beers_Ale = Beer_Brew_Combo %>% filter(grepl("\\bAle\\b | \\bIPA\\b", Style))

# Create new column to identify IPAs vs other Ale
Beers_Ale$Ale_Type = Beers_Ale$Style
# Rename new Other_Ale Column variables - IPA or Other
Beers_Ale$Ale_Type =  ifelse(grepl("IPA",Beers_Ale$Style),"IPA","Other_Ale")

# Count total number of IPA beers = 571 and Other Ale beers = 260
Beers_Ale %>% count(Ale_Type)

# Create a new dataframe removing the NA's
# Recount total number with ABV and IBU values of IPA beers = 392 and Other Ale beers = 166 
Beers_Ale_Adj = Beers_Ale %>% filter_at(vars(ABV,IBU),all_vars(!is.na(.)))
Beers_Ale_Adj %>% count(Ale_Type)


# Use KNN classification to investigate relationship of IBU and ABV between IPAs and other types of Ale
# First, assess relationship via a scatterplot 
Beers_Ale_Adj %>% ggplot(aes(x = ABV, y = IBU, color = Ale_Type)) + geom_point() + geom_smooth()
# It appears the higher the ABV and IBU value the higher the likelihood of being an IPA
# This is more evident with the IPA beers
# The lower ABV and IBU values are more evident for the non-IPA beers / other ale beers

# Conduct a KNN analysis
# Need to elaborate somewhere about the "why" and "what" about KNN.......
trainInd_Beers = sample(seq(1,558,1), .7*558) 
traindf_Beers = Beers_Ale_Adj[trainInd_Beers,]
testdf_Beers = Beers_Ale_Adj[-trainInd_Beers,]
summary(testdf_Beers)
summary(traindf_Beers)

# External CV, k = 10 
# Explain what we are doing here.....
classifications = knn(traindf_Beers[,c(4,5)],testdf_Beers[,c(4,5)],traindf_Beers$Ale_Type, prob = TRUE, k = 10)
table(classifications,testdf_Beers$Ale_Type)
confusionMatrix(table(classifications,testdf_Beers$Ale_Type))

#Internal CV, k = 10
# Explain what we are doing here....
classifications = knn.cv(Beers_Ale_Adj[,c(4,5)],Beers_Ale_Adj$Ale_Type, prob = TRUE, k = 10)
table(classifications,Beers_Ale_Adj$Ale_Type)
confusionMatrix(table(classifications,Beers_Ale_Adj$Ale_Type))


# Question 9: Knock their socks off!  Find one other useful inference from the data that you feel Budweiser may be able to find value in.  You must convince them why it is important and back up your conviction with appropriate statistical evidence.
# Some ideas to give them as to where they can focus their sales efforts: 
# Region breakdown - where should they focus
# Analyze cities in top 10 to know where to focus or do this after looking at region
# Assess number of unique beers


# load the Region csv file which we pulled in from our expert database which we thought would be additive for our client and the info they provided
Region = read.csv(file.choose(), header = TRUE)
summary(Region)

# merge Beers and Breweries data frames with Region
Beer_Brew_Region = merge(Beer_Brew_Combo, Region,c("State"))
summary(Beer_Brew_Region)

# plot data to see which region has most breweries
Beer_Brew_Region %>% ggplot(aes(x = Region)) + geom_bar(color="black", fill = "red", binwidth = 20)

# plot data to see which cities in West Region have most breweries
Beer_Brew_Region %>% filter(Region == "West Region") %>% ggplot(aes(x = City)) + geom_bar(color="black", fill = "red", binwidth = 20)

# difficult to gain insight from plot so looked at count of top cities in West Region
Beer_Brew_Region %>% filter(Region == "West Region") %>% count(City, sort = TRUE)
head(Beer_Brew_Region %>% filter(Region == "West Region") %>% count(City, sort = TRUE), 20)

# repeated without West Region filter
Beer_Brew_Region %>%  count(City, sort = TRUE)
head(Beer_Brew_Region %>%  count(City, sort = TRUE), 20)

# maybe we could pick out the top cities in the West Region to suggest focusing on????  I'm open to whatever for this one......